---
- name: start docker service
  service:
    name: docker
    state: started
    
- name: copying resource directory to target server /tmp location
  copy: src=static_files/resources/  dest=/tmp/resources/ follow=true mode=0777
- name: install python-pip
  shell: zypper -n install python-pip
- name: install ansible docker module using python pip
  shell: yes | pip install docker-py

- name: build the image
  docker_image: 
    name: apache2-latest
    tag: devops
    path: /tmp/resources
- name: running conatiner
  docker_container:
    name: apache2-conatiner
    image: apache2-latest:devops
    state: started
    recreate: yes
    exposed_ports:
      - 80
