---
- name: start docker service
  service:
    name: docker
    state: started
    
- name: copying resource directory to target server /tmp location
  copy: src=static_files/resources/*  dest=/tmp/resources/ follow=true mode=0777

- name: build the image
  docker_image: 
    name: nginix-latest
    tag: devops
    path: /tmp/resources
    state: present

- name: run the site in a docker container
  docker:
    name: website
    image: "nginix-latest:devops"
    state: reloaded
    publish_all_ports: yes